// src/front-end/src/lit/components/video/camera-preview.ts
import { LitElement, html, css } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { logger } from '../../../infrastructure/observability/otel-logger';

type CameraPreviewFilterState = {
  id: string;
  parameters: Record<string, string>;
};

interface StatsManager {
  updateCameraStatus(status: string, type: 'success' | 'error' | 'warning' | 'inactive'): void;
}

interface ToastManager {
  error(title: string, message: string): void;
}

type FrameCallback = (base64data: string, width: number, height: number, timestamp: number) => void;

@customElement('camera-preview')
export class CameraPreview extends LitElement {
  @property({ type: Number }) width = 640;
  @property({ type: Number }) height = 480;
  @property({ type: Number }) fps = 15;
  @property({ type: Number }) quality = 0.7;
  @property({ type: String, attribute: false }) heroSrc = '';

  @query('video') private videoElement!: HTMLVideoElement;
  @query('canvas') private canvasElement!: HTMLCanvasElement;

  @state() private isProcessing = false;

  private statsManager: StatsManager | null = null;
  private toastManager: ToastManager | null = null;
  private stream: MediaStream | null = null;
  private remoteStream: MediaStream | null = null;
  private frameInterval: number | null = null;
  private lastFrameTime = 0;
  private onFrameCallback: FrameCallback | null = null;
  private activeFilters: CameraPreviewFilterState[] = [];

  static styles = css`
    :host {
      display: contents;
    }

    video {
      width: 100%;
      height: 100%;
      object-fit: contain;
      background: black;
    }

    canvas {
      display: none;
    }
  `;

  render() {
    return html`
      <slot name="hero-image"></slot>
      <video autoplay playsinline muted></video>
      <canvas></canvas>
    `;
  }

  setManagers(statsManager: StatsManager, toastManager: ToastManager): void {
    this.statsManager = statsManager;
    this.toastManager = toastManager;
  }

  setResolution(width: number, height: number): void {
    this.width = width;
    this.height = height;

    if (this.frameInterval) {
      this.stopCapture();
      this.startCapture(this.onFrameCallback!);
    }
  }

  async start(): Promise<boolean> {
    try {
      this.statsManager?.updateCameraStatus('Requesting access...', 'warning');

      if (!navigator.mediaDevices?.getUserMedia) {
        throw new Error('Camera API not available. Use HTTPS.');
      }

      this.stream = await navigator.mediaDevices.getUserMedia({
        video: {
          width: { ideal: 640 },
          height: { ideal: 480 },
          facingMode: 'user',
        },
      });

      // Wait for video element to be available
      if (!this.videoElement) {
        await this.updateComplete;
        if (!this.videoElement) {
          throw new Error('Video element not found');
        }
      }

      this.videoElement.srcObject = this.stream;
      await new Promise<void>((resolve) => (this.videoElement.onloadedmetadata = () => resolve()));
      await this.videoElement.play();
      await new Promise<void>((resolve) => setTimeout(resolve, 500));

      logger.info('Camera ready', {
        'camera.width': this.videoElement.videoWidth,
        'camera.height': this.videoElement.videoHeight,
      });

      this.statsManager?.updateCameraStatus('Active', 'success');

      this.dispatchEvent(
        new CustomEvent('camera-started', {
          bubbles: true,
          composed: true,
        })
      );

      return true;
    } catch (error) {
      logger.error('Camera error', {
        'error.message': error instanceof Error ? error.message : String(error),
      });

      let errorTitle = 'Camera Error';
      let errorMsg = '';

      if (error instanceof Error) {
        if (error.name === 'NotAllowedError') {
          errorTitle = 'Permission Denied';
          errorMsg = 'Please allow camera access in your browser settings';
        } else if (error.name === 'NotFoundError') {
          errorTitle = 'No Camera Found';
          errorMsg = 'No camera device detected on this system';
        } else if (error.name === 'NotReadableError') {
          errorTitle = 'Camera In Use';
          errorMsg = 'Camera is being used by another application. Please close it and try again';
        } else if (error.message) {
          errorMsg = error.message;
        }
      }

      this.toastManager?.error(errorTitle, errorMsg);

      if (this.statsManager) {
        const shortMsg = errorTitle.replace(' Error', '').substring(0, 20);
        this.statsManager.updateCameraStatus(shortMsg, 'error');
      }

      this.dispatchEvent(
        new CustomEvent('camera-error', {
          bubbles: true,
          composed: true,
          detail: { error, errorTitle, errorMsg },
        })
      );

      return false;
    }
  }

  stop(): void {
    if (this.stream) {
      this.stream.getTracks().forEach((track) => track.stop());
      this.stream = null;
    }

    this.stopCapture();

    if (this.videoElement?.srcObject) {
      this.videoElement.srcObject = null;
    }
    this.remoteStream = null;

    this.statsManager?.updateCameraStatus('Inactive', 'inactive');
  }

  startCapture(onFrameCallback: FrameCallback): void {
    if (!this.canvasElement || !this.videoElement) return;

    this.onFrameCallback = onFrameCallback;
    const ctx = this.canvasElement.getContext('2d', { willReadFrequently: true });
    if (!ctx) return;

    this.canvasElement.width = this.width;
    this.canvasElement.height = this.height;

    logger.info('Starting capture', {
      'capture.width': this.width,
      'capture.height': this.height,
    });

    this.frameInterval = window.setInterval(() => {
      if (!this.videoElement || !this.videoElement.videoWidth || this.isProcessing) return;

      this.lastFrameTime = performance.now();

      ctx.drawImage(this.videoElement, 0, 0, this.width, this.height);
      const dataUrl = this.canvasElement.toDataURL('image/jpeg', this.quality);
      const base64data = dataUrl.split(',')[1];

      if (this.onFrameCallback) {
        this.onFrameCallback(base64data, this.width, this.height, this.lastFrameTime);
      }

      this.dispatchEvent(
        new CustomEvent('frame-captured', {
          bubbles: true,
          composed: true,
          detail: {
            base64data,
            width: this.width,
            height: this.height,
            timestamp: this.lastFrameTime,
          },
        })
      );
    }, 1000 / this.fps);
  }

  stopCapture(): void {
    if (this.frameInterval !== null) {
      clearInterval(this.frameInterval);
      this.frameInterval = null;
    }
  }

  setProcessing(isProcessing: boolean): void {
    this.isProcessing = isProcessing;
  }

  setRemoteStream(stream: MediaStream | null): void {
    this.remoteStream = stream;
    if (this.videoElement) {
      if (!this.remoteStream) {
        this.videoElement.srcObject = this.stream;
        if (this.videoElement.srcObject) {
          void this.videoElement.play().catch(() => undefined);
        }
        return;
      }

      const probe = document.createElement('video');
      probe.muted = true;
      probe.playsInline = true;
      probe.srcObject = this.remoteStream;

      void probe
        .play()
        .then(
          () =>
            new Promise<boolean>((resolve) => {
              const deadline = window.setTimeout(() => resolve(false), 1500);
              const checkPlayback = () => {
                if (probe.readyState >= HTMLMediaElement.HAVE_CURRENT_DATA || probe.videoWidth > 0) {
                  clearTimeout(deadline);
                  resolve(true);
                  return;
                }
                window.requestAnimationFrame(checkPlayback);
              };
              checkPlayback();
            })
        )
        .then((isPlayable) => {
          if (!isPlayable || !this.videoElement) {
            return;
          }
          this.videoElement.srcObject = this.remoteStream;
          void this.videoElement.play().catch(() => undefined);
        })
        .catch(() => undefined)
        .finally(() => {
          probe.srcObject = null;
        });
    }
  }

  setFilters(filters: CameraPreviewFilterState[]): void {
    this.activeFilters = filters;
  }

  getStream(): MediaStream | null {
    return this.stream;
  }

  getLastFrameTime(): number {
    return this.lastFrameTime;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'camera-preview': CameraPreview;
  }
}

// src/front-end/src/presentation/components/video/CameraPreview.tsx
import { useEffect, useRef } from 'react';
import type { ActiveFilterState } from '@/presentation/components/filters/FilterPanel';

type FrameCapturedPayload = {
  base64data: string;
  width: number;
  height: number;
  timestamp: number;
};

type CameraPreviewProps = {
  width?: number;
  height?: number;
  fps?: number;
  quality?: number;
  captureFrames?: boolean;
  remoteStream?: MediaStream | null;
  activeFilters?: ActiveFilterState[];
  onFrameCaptured: (payload: FrameCapturedPayload) => void;
  onStreamReady?: (stream: MediaStream) => void;
  onCameraStatus: (status: string, type: 'success' | 'error' | 'warning' | 'inactive') => void;
  onCameraError: (title: string, message: string) => void;
};

export function CameraPreview({
  width = 640,
  height = 480,
  fps = 15,
  quality = 0.7,
  captureFrames = true,
  remoteStream = null,
  activeFilters = [],
  onFrameCaptured,
  onStreamReady,
  onCameraStatus,
  onCameraError,
}: CameraPreviewProps) {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const intervalRef = useRef<number | null>(null);
  const onFrameCapturedRef = useRef(onFrameCaptured);
  const onStreamReadyRef = useRef(onStreamReady);
  const onCameraStatusRef = useRef(onCameraStatus);
  const onCameraErrorRef = useRef(onCameraError);

  useEffect(() => {
    onFrameCapturedRef.current = onFrameCaptured;
  }, [onFrameCaptured]);

  useEffect(() => {
    onCameraStatusRef.current = onCameraStatus;
  }, [onCameraStatus]);

  useEffect(() => {
    onStreamReadyRef.current = onStreamReady;
  }, [onStreamReady]);

  useEffect(() => {
    onCameraErrorRef.current = onCameraError;
  }, [onCameraError]);

  useEffect(() => {
    const video = videoRef.current;
    if (!video) {
      return;
    }

    if (!remoteStream) {
      video.srcObject = streamRef.current;
      if (video.srcObject) {
        void video.play().catch(() => undefined);
      }
      return;
    }

    let cancelled = false;
    const probe = document.createElement('video');
    probe.muted = true;
    probe.playsInline = true;
    probe.srcObject = remoteStream;

    const tryPromoteRemoteStream = async () => {
      try {
        await probe.play();
      } catch {
        return;
      }

      const isPlayable = await new Promise<boolean>((resolve) => {
        const deadline = window.setTimeout(() => resolve(false), 1500);

        const checkPlayback = () => {
          if (probe.readyState >= HTMLMediaElement.HAVE_CURRENT_DATA || probe.videoWidth > 0) {
            clearTimeout(deadline);
            resolve(true);
            return;
          }
          window.requestAnimationFrame(checkPlayback);
        };

        checkPlayback();
      });

      if (!cancelled && isPlayable) {
        video.srcObject = remoteStream;
        void video.play().catch(() => undefined);
      }
    };

    void tryPromoteRemoteStream();

    return () => {
      cancelled = true;
      probe.srcObject = null;
    };
  }, [remoteStream]);

  useEffect(() => {
    let cancelled = false;

    const startCamera = async () => {
      try {
        onCameraStatusRef.current('Requesting access...', 'warning');
        if (!navigator.mediaDevices?.getUserMedia) {
          throw new Error('Camera API not available. Use HTTPS.');
        }

        const stream = await navigator.mediaDevices.getUserMedia({
          video: { width: { ideal: 640 }, height: { ideal: 480 }, facingMode: 'user' },
        });
        if (cancelled) {
          stream.getTracks().forEach((track) => track.stop());
          return;
        }
        streamRef.current = stream;

        const video = videoRef.current;
        const canvas = canvasRef.current;
        if (!video || !canvas) {
          throw new Error('Camera preview elements are not ready');
        }

        video.srcObject = stream;
        await new Promise<void>((resolve) => {
          video.onloadedmetadata = () => resolve();
        });
        await video.play();
        onStreamReadyRef.current?.(stream);

        canvas.width = width;
        canvas.height = height;
        onCameraStatusRef.current('Active', 'success');

        const ctx = canvas.getContext('2d', { willReadFrequently: true });
        if (!ctx) {
          throw new Error('Camera canvas context is not available');
        }

        if (captureFrames) {
          intervalRef.current = window.setInterval(() => {
            if (!video.videoWidth) {
              return;
            }
            const timestamp = performance.now();
            ctx.drawImage(video, 0, 0, width, height);
            const dataUrl = canvas.toDataURL('image/jpeg', quality);
            const base64data = dataUrl.split(',')[1] ?? '';
            onFrameCapturedRef.current({ base64data, width, height, timestamp });
          }, 1000 / fps);
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        onCameraErrorRef.current('Camera Error', message);
        onCameraStatusRef.current('Camera Error', 'error');
      }
    };

    void startCamera();
    return () => {
      cancelled = true;
      if (intervalRef.current !== null) {
        clearInterval(intervalRef.current);
        intervalRef.current = null;
      }
      if (streamRef.current) {
        streamRef.current.getTracks().forEach((track) => track.stop());
        streamRef.current = null;
      }
      if (videoRef.current) {
        videoRef.current.srcObject = null;
      }
      onCameraStatusRef.current('Inactive', 'inactive');
    };
  }, [captureFrames, fps, height, quality, width]);

  return (
    <>
      <video
        ref={videoRef}
        autoPlay
        playsInline
        muted
        style={{
          width: '100%',
          height: '100%',
          objectFit: 'contain',
          background: 'black',
        }}
      />
      <canvas ref={canvasRef} style={{ display: 'none' }} />
    </>
  );
}
